[project]
name = "juliogarbers-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "nbclient>=0.10.4",
    "nbformat>=5.10.4",
    "plotly>=6.5.2",
    "polars>=1.0.0",
]
